println("Contains:  ", occursin("es", "test"))
println("Count:     ", count("t", "test"))
println("HasPrefix: ", startswith("test", "te"))
println("HasSuffix: ", endswith("test", "st"))
println("Index:     ", findfirst('e', "test") - 1)
println("Join:      ", join(["a", "b"], "-"))
println("Repeat:    ", "a"^5)
println("Replace:   ", replace("foo", "o" => "0"))
println("Replace:   ", replace("foo", "o" => "0", count=1))
println("Split:     ", String.(split("a-b-c-d-e", "-")))
println("ToLower:   ", lowercase("TEST"))
println("ToUpper:   ", uppercase("test"))

println("Len: ", length("hello"))
println("Char: ", Int(codeunit("hello", 2)))
